### PR TITLE
Add new features which generates the images as per the hint related to the word.

### PR DESCRIPTION
**Pull request by aryyan0701**
# Contribution to Guess the Word Project

## Introduction

I have added a new feature to the Guess the Word project that generates hinted images to assist users in guessing the word. This enhancement provides a visual clue to make the game more engaging and enjoyable.

### Hinted Images

I introduced a new functionality that associates each word with an image. When a new word is displayed, the corresponding image is also shown to provide a hint related to the word.

### Implementation

- Modified the JavaScript code to dynamically load and display the image associated with each word.

```javascript
// Example code snippet
// Remove the previous image if it exists
    const previousImage = document.querySelector(".content img");
    if (previousImage) {
        previousImage.remove();
    }

// Set image source if available
if (ranItem.imgsrc) {
  let img = document.createElement("img");
  img.src = ranItem.imgsrc;
  img.alt = "Word Image";
  content.appendChild(img);
}

// set the image resource 
let wordList = [
    {
        word: "python",
        hint: "programming language",
        imgsrc:"./assets/python.jpg"
    },
]

### CODE REVIEW

**Comment by khardikk** [comment]
The feature looks good, just one thing before merging, can you add a hint button which on clicked will display the image, otherwise it will not, this will act as a good UX.

**Comment by aryyan0701** [comment]
ok i'll add the hint button.

**Comment by aryyan0701** [comment]
check out this hint button that has been added Is it okay now?

**Comment by khardikk** [comment]
> check out this hint button that has been added Is it okay now?

Please add the styling according to the current button present, keep the size smaller

**Review by khardikk — APPROVED** [review]
Looks good to me

**Pull request merged**
